/**
 * 선박 데이터 — 선박관리카드(hwpx) + 사진 기반 실제 제원
 *
 * 가격은 미확인 → null.
 * features는 관리카드·사진으로 확인된 것만.
 */

import type { Vessel } from "@/lib/supabase";

export const VESSEL_OVERRIDES: Record<
  string,
  Partial<Omit<Vessel, "vessel_images">>
> = {
  "suyeon-1": {
    title: "수연1호",
    ship_number: "ICR-031410",
    vessel_type: "예인선(강선)",
    use_cases: ["construction"],
    tagline: "예항력(BOLLARD PULL) 9.66t · 근해 예인·화물",
    year_built: 1983,
    length_m: 20.09,
    tonnage: 33,
    horsepower: 1414,
    engine_power: null,
    capacity: 4,
    location: "인천 연안부두",
    description:
      "1983년 일본 본와조선 건조, 강선.\n1,414마력 주기관 탑재, 생활발전기 완비.\n예항력(BOLLARD PULL) 9.66톤.\n인천항 기반 근해 예인·화물 운송.\n\n주요 작업 이력:\n· 2026.4 전남 목포 우이도 풍력발전소 건설현장 투입\n· 2025.4 한강 준설 아라뱃길 (유호산업)\n· 2024.11 광양 작업 (대양건설)\n· 2023.12 충남 태안 (현대스틸, 임대)",
    features: [
      "1,414마력 주기관",
      "생활발전기",
      "경유필터",
      "오일필터",
      "조타실",
      "기관실",
      "예항력(BOLLARD PULL) 9.66톤",
      "선원 4명 승선",
    ],
    rent_price_per_day: null,
    sale_price: null,
    type: "both",
    is_featured: true,
  },
  "suyeon-3": {
    title: "수연3호",
    ship_number: "ICC-251825",
    vessel_type: "기타선(통선)(FRP)",
    use_cases: ["survey", "construction"],
    tagline: "디젤+내장 스크류 · 장거리 통선",
    year_built: 2020,
    length_m: 8.54,
    tonnage: 3.01,
    horsepower: 180,
    engine_power: "대우 132kW/180hp 디젤 (선내기 1대)",
    capacity: 8,
    location: "인천 연안부두",
    description:
      "2020년 인천 제일산업공사 건조, FRP 통선.\n대우 132kW/180hp 디젤 1기 + 내장 스크류(나선) 추진 — 동급 통선 중 출력·안정성 우수.\n8.54m × 2.38m × 0.5m, 총톤수 3.01톤. 임시승선 7명 + 선원 1명.\n\n특징:\n· 동기종 4척(8·9호, 인천9호) 중 유일하게 디젤 + 내장 스크류 → 장거리·중하중 작업 유리\n· 2025년 7월 기타선(통선) 등록 변경 — 해상공사 통선·측량선 임대 적합\n· 선외기 어선 용도 매도도 가능\n· 인천 연안부두 제일산업공사 앞 상시 계류, 관리상태 양호(상)\n· 해운업 등록증 ICB2088 (인천지방해수청 18.10.15)",
    features: [
      "대우 디젤 선내기 1기 (132kW/180hp)",
      "내장 스크류 추진(나선)",
      "임시승선 7명 + 선원 1명",
      "해운업 등록 ICB2088",
    ],
    rent_price_per_day: null,
    sale_price: null,
    type: "both",
    is_featured: false,
  },
  "suyeon-5": {
    title: "수연5호",
    ship_number: "ICR-952399",
    vessel_type: "예인선(FRP)",
    use_cases: ["construction"],
    tagline: "예항력 8.8t · 국내 최초 FRP 예인선",
    year_built: 1995,
    length_m: 18,
    tonnage: 24,
    horsepower: 1000,
    engine_power: "500마력 × 2대",
    capacity: 16,
    location: "인천 연안부두",
    description:
      "1995년 경남 고성 세모조선 건조, FRP선.\n2026.9.3 예인선 항해검사를 통과한 국내 최초 FRP 예인선으로, 근해 예인·화물 운송에 투입.\n선실, 조타실 완비. 여객12명+선원4명 승선 가능.\n항해구역: 연해(국내).\n\n주요 작업 이력:\n· 2025.5 전북 구시포 현장 (삼원개발, 은성오엔씨 임대)\n· 2024.3 제주도 (현대스틸, 임대)",
    features: [
      "예항력(Bollard Pull) 8.8톤",
      "선실",
      "조타실",
      "여객 12명 + 선원 4명 승선",
      "연해 항해구역",
    ],
    rent_price_per_day: null,
    sale_price: null,
    type: "both",
    is_featured: true,
  },
  "suyeon-6": {
    title: "수연6호",
    ship_number: "ICR-231819",
    vessel_type: "기선(FRP)",
    use_cases: ["survey", "construction"],
    tagline: "환경정화·측량 운용 이력",
    year_built: 2010,
    length_m: 14.4,
    tonnage: 14,
    horsepower: 793,
    engine_power: null,
    capacity: 16,
    location: "인천 연안부두",
    description:
      "2010년 전남 여수 신우조선 건조, FRP선.\n선원실, 조타실 완비. 여객12명+선원4명 승선 가능.\n환경정화 활동 참여 이력.\n항해구역: 연해(국내).\n\n주요 작업 이력:\n· 2025.6 완도 해상 지오뷰 측량작업\n· 2024.4 전북 (UST 21, 임대)",
    features: [
      "선원실",
      "조타실",
      "주기관",
      "환경정화 참여",
      "여객 12명 + 선원 4명 승선",
      "연해 항해구역",
    ],
    rent_price_per_day: null,
    sale_price: null,
    type: "both",
    is_featured: true,
  },
  "suyeon-8": {
    title: "수연8호",
    ship_number: "ICC-251826",
    vessel_type: "기타선(통선)(FRP)",
    use_cases: ["survey", "construction"],
    tagline: "HONDA 150 · 기동성 우수",
    year_built: 2020,
    length_m: 8.63,
    tonnage: 2.09,
    horsepower: 150,
    engine_power: "HONDA 150 선외기",
    capacity: 4,
    location: "인천 연안부두",
    description:
      "2020년 인천 제일산업공사 건조, FRP 통선.\nHONDA 150 선외기 1기, 휘발유. 임시승선 3명 + 선원 1명.\n8.63m × 2.38m × 0.8m, 총톤수 2.09톤.\n\n특징:\n· 9호와 동일 선체에 작은 톤수 → 기동성·연비 우수\n· 선외기 단순 구조로 정비 부담 최소\n· 4인 측량팀·소규모 연락선으로 적합\n· 2025년 7월 기타선(통선) 등록 변경, 관리상태 양호(상)\n· 해운업 등록증 ICB2088",
    features: [
      "HONDA 150 선외기 1기",
      "휘발유",
      "임시승선 3명 + 선원 1명",
      "해운업 등록 ICB2088",
    ],
    rent_price_per_day: null,
    sale_price: null,
    type: "both",
    is_featured: false,
  },
  "suyeon-9": {
    title: "수연9호",
    ship_number: "ICC-251827",
    vessel_type: "기타선(통선)(FRP)",
    use_cases: ["survey", "construction"],
    tagline: "YAMAHA 250 · 최대급 선외기 출력",
    year_built: 2020,
    length_m: 8.63,
    tonnage: 2.37,
    horsepower: 250,
    engine_power: "YAMAHA 250 선외기",
    capacity: 4,
    location: "인천 연안부두",
    description:
      "2020년 인천 제일산업공사 건조, FRP 통선.\nYAMAHA 250 선외기 1기, 휘발유. 임시승선 3명 + 선원 1명.\n8.63m × 2.38m × 0.8m, 총톤수 2.37톤.\n\n특징:\n· 8호와 동일 선체에 YAMAHA 250 탑재 — 인천9호와 함께 선외기 최대 출력\n· 짧은 거리 빠른 이동·작업 적합\n· 4인 측량팀·소규모 연락선으로 적합\n· 2025년 7월 기타선(통선) 등록 변경, 관리상태 양호(상)\n· 해운업 등록증 ICB2088",
    features: [
      "YAMAHA 250 선외기 1기",
      "휘발유",
      "임시승선 3명 + 선원 1명",
      "해운업 등록 ICB2088",
    ],
    rent_price_per_day: null,
    sale_price: null,
    type: "both",
    is_featured: false,
  },
  "incheon-9": {
    title: "인천 9호",
    ship_number: "ICC-141823",
    vessel_type: "기타선(통선)(FRP)",
    use_cases: ["survey", "construction"],
    tagline: "선외기 250마력 · 최경량 통선",
    year_built: 2020,
    length_m: 8.5,
    tonnage: 1.67,
    horsepower: 250,
    engine_power: "250마력 선외기",
    capacity: 3,
    location: "인천 연안부두",
    description:
      "2020년 인천 제일산업공사 건조, FRP 통선.\n250마력 선외기 1기. 임시승선 2명 + 선원 1명.\n길이 8.5m, 총톤수 1.67톤 — 보유 통선 중 최경량.\n\n특징:\n· 컴팩트한 크기로 좁은 수역·접안 작업·소형 부두 출입 유리\n· 단거리 연락·소규모 측량·근접 점검에 최적\n· 3인 탑승, 250마력 출력으로 톤수 대비 추진력 우수\n· 2025년 7월 기타선(통선) 등록 변경, 관리상태 양호(상)\n· 해운업 등록증 ICB2088",
    features: [
      "250마력 선외기 1기",
      "임시승선 2명 + 선원 1명",
      "해운업 등록 ICB2088",
    ],
    rent_price_per_day: null,
    sale_price: null,
    type: "both",
    is_featured: false,
  },
  sinseong: {
    title: "신성호",
    ship_number: "ICR-121820",
    vessel_type: "기타선(FRP)",
    use_cases: ["survey", "construction"],
    tagline: "도선 12명 · 측량업체 정기 임대",
    year_built: 1989,
    length_m: 13.84,
    tonnage: 10,
    horsepower: 550,
    engine_power: null,
    capacity: 12,
    location: "인천 연안부두",
    description:
      "1989년 전남 고흥 형제조선 건조, FRP선.\n도선(임시승선10명, 선원2명). 선실, 조타실 완비.\n연해구역(국내) 항해.\n\n주요 작업 이력:\n· 2025.8 경남 거제 작업 (지오스토리)\n· 2024.6 강원 고성 올포랜드(주)",
    features: [
      "선실",
      "조타실",
      "주기관",
      "임시승선 10명 + 선원 2명",
      "연해 항해구역",
    ],
    rent_price_per_day: null,
    sale_price: null,
    type: "both",
    is_featured: true,
  },
  youngjin: {
    title: "영진호",
    ship_number: "ICC-121839",
    vessel_type: "기타선(통선)(FRP)",
    use_cases: ["survey"],
    tagline: "지오스토리 정기 임대 통선",
    year_built: 1997,
    length_m: 14.38,
    tonnage: 12,
    horsepower: 410,
    engine_power: "디젤 410PS(301kW)",
    capacity: 10,
    location: "인천 연안부두",
    description:
      "1997년 전남 고흥 남해FRP조선소 건조, FRP선.\n디젤 410PS(301kW) 1기.\n통선(여객8명, 선원2명).\n\n주요 작업 이력:\n· 2025.6 전북 군산 위도 (지오스토리)\n· 2024.3 전남 영광 (지오스토리)\n· 2023.3 거제 (지오스토리)",
    features: [
      "디젤 410PS(301kW) 주기관",
      "여객 8명 + 선원 2명 승선",
    ],
    rent_price_per_day: null,
    sale_price: null,
    type: "both",
    is_featured: false,
  },
  "jinyang-2": {
    title: "진양2호",
    ship_number: "ICC-090894",
    vessel_type: "기타선(통선)(강선)",
    use_cases: ["survey", "construction"],
    tagline: "강선 41년 베테랑 · 여객 10명",
    year_built: 1984,
    length_m: 12.1,
    tonnage: 7.98,
    horsepower: 360,
    engine_power: "디젤 (경유)",
    capacity: 11,
    location: "인천 연안부두",
    description:
      "1984년 일본 장포조선 건조, 강선 통선.\n12.1m × 3.00m × 1.10m, 총톤수 7.98톤. 여객 10명 + 선원 1명.\n경유 디젤 추진. 41년 운항 베테랑.\n\n특징:\n· 강선 선체로 5톤급 통선 중 내구성·안정성 최고\n· 보유 통선 중 유일하게 여객 10명 동시 수송 가능\n· 5척 중 유일하게 실제 임대 운용 실적 보유\n· 2021.8 수연선박 인수\n· 해운업 등록증 ICB2088 (인천지방해수청 18.10.15)\n\n주요 작업 이력:\n· 2025.11.26 한강 아라뱃길 (유호건설, 해상공사)\n· 2024.3.9 인천항 출항 → 전남 영광 (지오스토리, 해상측량)",
    features: [
      "강선 선체",
      "디젤 (경유)",
      "여객 10명 + 선원 1명 승선",
      "보유 통선 최대 (12.1m / 7.98톤)",
      "실제 임대 운용 실적 보유",
      "해운업 등록 ICB2088",
    ],
    rent_price_per_day: null,
    sale_price: null,
    type: "both",
    is_featured: true,
  },
};
